site_name: STAIA

# themes: https://pawamoy.github.io/mkdocs-gallery/
# original: material
theme:
  name: readthedocs

plugins:
  - search
  - mkdocs-jupyter 
  - mkdocstrings:
      handlers:
        python:
          paths: ["/exports/archive/hg-funcgenom-research/evonk/functionalAPI"] 
          options:
            show_submodules: false
            filters:
              - "!^_"
            show_source: true
            docstring_style: numpy

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Tutorials:
      - Tutorial: tutorials/tutorial.ipynb
  - Documentation: 
      - Read Data: documentation/read_spatialobject.md
      - Add Nuclei: documentation/add_nuclei.md
      - Size Normalization: documentation/size_normalization.md
      - Compute Metrics: documentation/metrics.md
      - Adjusted Rand Index: documentation/ari.md
      - QC: documentation/qc.md
      - Plotting: documentation/plot.md
      - Neighbor Analysis: documentation/neighbor_analysis.md
      - Assigning Labels: documentation/assigning_labels.md
      - Spatial Clustering: documentation/spatial_clustering.md
      - Cell Communication: documentation/cell_communication.md
      - Pseudobulk DE: documentation/pseudobulk.md
